version: 2

general:
  # Get Hypixel API key by creating one via dashboard.hypixel.net
  hypixelApiKey: '3351b5b0-9d23-4103-a4b7-971c8e82c560'
  # Share basic anonymous metrics to display on the project main page as a way to show its popularity.
  # All metrics are anonymous and are limited to counting and never about anything specific
  shareMetrics: true

discord:
  # Create new discord bot from https://discordapp.com/developers and generate a secret key
  key: 'MTQyMDQyNjg1NTIwNjM1NTExNQ.GXGHp8.qhiQrqb51HZn-uIuXiTCoHzo9fgyMcXwAGGZZo'
  # Discord ID of the USER who will have ADMIN permission
  adminIds: ['1154184241496739840', '625798333742448641', '818826907993767986']

prometheus:
  enabled: false
  port: 9095
  # Prefix for prometheus metrics database
  prefix: '$'
